### ISSUE TITLE
ModuleNotFoundError when using agentMET4FOF from PyPi

### ISSUE THREAD

**Issue by mgrub** [bangxiangyong/agentMET4FOF#59]
After setting up a clean python-venv and then `pip install agentMET4FOF`, execution of `import agentMET4FOF.agents` yields: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "%userprofile%\python_venv\agentmet4fof\lib\site-packages\agentMET4FOF\agents.py", line 24, in <module>
    from agentMET4FOF.dashboard.Dashboard import AgentDashboard as AgentDashboard        
  File "%userprofile%\python_venv\agentmet4fof\lib\site-packages\agentMET4FOF\dashboard\Dashboard.py", line 6, in <module>
    from agentMET4FOF.dashboard.Dashboard_ml_exp import get_ml_exp_layout, prepare_ml_exp_callbacks, get_experiments_list
  File "%userprofile%\python_venv\agentmet4fof\lib\site-packages\agentMET4FOF\dashboard\Dashboard_ml_exp.py", line 15, in <module>
    from agentMET4FOF.develop.ML_Experiment import load_experiment
ModuleNotFoundError: No module named 'agentMET4FOF.develop'
```

Details about the system:
OS: Windows 10 Pro 64bit
Python: 3.7.7 and 3.8.1
agentMET4FOF: 0.1.4

Current Workaround:
Use agentMET4FOF from a clone of the github-repo:
- clone the repo to <directory_of_your_choice>
- set up a python-venv with all requirements for agentMET4FOF
- add <directory_of_your_choice> to the PYTHONPATH (either by setting a system variable or by using `import sys;sys.path.append("<directory_of_your_choice>")`

**Comment by BjoernLudwigPTB** [comment]
This is now resolved. Just issue from the commandline with activated venv

```shell
(my_agent_venv) $ pip install --upgrade agentMET4FOF
```
