### ISSUE TITLE
Executing run_dashboard.py brings up error

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [bangxiangyong/agentMET4FOF#8]
When I execute `python`[`run_dashboard.py`](https://github.com/bangxiangyong/agentMet4FoF/blob/master/agentMET4FOF/run_dashboard.py#L10) in the console I get the following output periodically:

```
Unable to connect to existing NameServer...
 * Serving Flask app "dashboard.Dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Jul/2019 17:24:32] "GET /_favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2019 17:24:33] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2019 17:24:33] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2019 17:24:33] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2019 17:24:33] "POST /_dash-update-component HTTP/1.1" 204 -
127.0.0.1 - - [30/Jul/2019 17:24:33] "POST /_dash-update-component HTTP/1.1" 204 -
127.0.0.1 - - [30/Jul/2019 17:24:33] "POST /_dash-update-component HTTP/1.1" 204 -
[2019-07-30 17:24:33,106] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "PATH\TO\MY\ENV\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "PATH\TO\MY\ENV\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "PATH\TO\MY\ENV\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "PATH\TO\MY\ENV\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "PATH\TO\MY\ENV\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "PATH\TO\MY\ENV\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "PATH\TO\MY\ENV\lib\site-packages\dash\dash.py", line 1147, in dispatch
    response.set_data(self.callback_map[output]['callback'](*args))
  File "PATH\TO\MY\ENV\lib\site-packages\dash\dash.py", line 1033, in add_context
    output_value = func(*args, **kwargs)
  File "PATH\TO\MY\REPOS\Met4FoF_Code\agentMet4FoF\dashboard\Dashboard.py", line 423, in plot_monitor_graphs
    if agentNetwork._get_mode() != "Running" and n_interval > 0:
  File "PATH\TO\MY\REPOS\Met4FoF_Code\agentMet4FoF\agents\AgentMET4FOF.py", line 653, in _get_mode
    return self._get_controller().get_attr('current_state')
  File "PATH\TO\MY\REPOS\Met4FoF_Code\agentMet4FoF\agents\AgentMET4FOF.py", line 789, in _get_controller
    self._controller = self.ns.proxy('AgentController')
AttributeError: 'int' object has no attribute 'proxy'
127.0.0.1 - - [30/Jul/2019 17:24:33] "POST /_dash-update-component HTTP/1.1" 500 -
```

Do we still need this script? If so we should update it.

**Comment by bangxiangyong** [comment]
It's not really a bug, it's reporting an error because there is no existing AgentNetwork to connect to. Thanks for pointing it out, should make it clearer in the logs to indicate what's happening..

**Comment by BjoernLudwigPTB** [comment]
This is resolved by just adding a comment and however inserting the IP as a parameter for connecting to a remote agent, since that is the one use case, we could come up with.

**Comment by bangxiangyong** [comment]
Should be resolved with this:

https://github.com/bangxiangyong/agentMET4FOF/pull/33/commits/31c85b878e101aa825ceedf5a6f7a5e9497fd3a2
